"""change avatar_path to avatar_data

Revision ID: b0945857fb2a
Revises: dae7a9f5b3c7
Create Date: 2025-01-04 07:40:16.494160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0945857fb2a'
down_revision = 'dae7a9f5b3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_practice_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('last_practice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_practice', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('last_practice_at')
        batch_op.drop_column('avatar_data')

    # ### end Alembic commands ###
