"""add user profile fields

Revision ID: dae7a9f5b3c7
Revises: 
Create Date: 2025-01-04 07:05:00.912334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae7a9f5b3c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_replies', schema=None) as batch_op:
        batch_op.drop_index('ix_forum_replies_created_at')
        batch_op.drop_index('ix_forum_replies_post_id')
        batch_op.drop_index('ix_forum_replies_user_id')

    op.drop_table('forum_replies')
    op.drop_table('study_record')
    op.drop_table('user')
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_forum_posts_created_at')
        batch_op.drop_index('ix_forum_posts_user_id')

    op.drop_table('forum_posts')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('reading_records', schema=None) as batch_op:
        batch_op.alter_column('practice_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('topic_records', schema=None) as batch_op:
        batch_op.alter_column('practice_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('grammar_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('content_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('relevance_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('zodiac_sign', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mbti', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')
        batch_op.drop_column('bio')
        batch_op.drop_column('mbti')
        batch_op.drop_column('zodiac_sign')
        batch_op.drop_column('birthday')

    with op.batch_alter_table('topic_records', schema=None) as batch_op:
        batch_op.alter_column('relevance_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('content_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('grammar_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('practice_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('reading_records', schema=None) as batch_op:
        batch_op.alter_column('practice_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    op.create_table('forum_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('reply_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_index('ix_forum_posts_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_forum_posts_created_at', ['created_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('study_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_input', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('accuracy_score', sa.FLOAT(), nullable=True),
    sa.Column('fluency_score', sa.FLOAT(), nullable=True),
    sa.Column('completeness_score', sa.FLOAT(), nullable=True),
    sa.Column('pronunciation_score', sa.FLOAT(), nullable=True),
    sa.Column('grammar_score', sa.FLOAT(), nullable=True),
    sa.Column('content_score', sa.FLOAT(), nullable=True),
    sa.Column('relevance_score', sa.FLOAT(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_replies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('is_ai_reply', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_replies', schema=None) as batch_op:
        batch_op.create_index('ix_forum_replies_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_forum_replies_post_id', ['post_id'], unique=False)
        batch_op.create_index('ix_forum_replies_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
